name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'sudhanportfoliowebsite'
  BUCKET_NAME: 'www.sudharsana.dev'
  SERVICE_ACCOUNT: 'github-actions-deployer@sudhanportfoliowebsite.iam.gserviceaccount.com'
  WIF_PROVIDER: '//iam.googleapis.com/projects/254598432060/locations/global/workloadIdentityPools/github-pool-new/providers/github'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Authorize with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Upload build to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: './build'
          destination: ${{ env.BUCKET_NAME }}
          parent: false
          glob: '**'